import typing

from _typeshed import Incomplete
from joblib.disk import mkdirp as mkdirp

def format_time(t: float) -> str: ...
def short_format_time(t: float) -> str: ...
def pformat(obj: typing.Any, indent: int = ..., depth: int = ...) -> str: ...

class Logger:
    depth: Incomplete
    def __init__(self, depth: int = ..., name: str | None = ...) -> None: ...
    def warn(self, msg: typing.Any) -> None: ...
    def info(self, msg: typing.Any) -> None: ...
    def debug(self, msg: typing.Any) -> None: ...
    def format(self, obj: typing.Any, indent: int = ...) -> str: ...

class PrintTime:
    last_time: float
    start_time: float
    logfile: str
    def __init__(self, logfile: str | None = ..., logdir: str | None = ...) -> None: ...
    def __call__(self, msg: str = ..., total: bool = ...) -> None: ...
